### ISSUE TITLE
Change titlebar icons

### ISSUE THREAD

**Issue by karambaq** [actionless/oomox#106]
Is there a way to customize  maximize, minimize buttons on the title?

**Comment by actionless** [comment]
There is no way except for manually replacing the assets.

**Comment by karambaq** [comment]
@actionless Yeah, in which folder I need to do this?

**Comment by actionless** [comment]
here, choose the subdirectory depending on your WM/DE:
https://github.com/actionless/oomox-gtk-theme/tree/master/src

**Comment by karambaq** [comment]
@actionless I use bspwm, I think I need to replace it in gtk-3.* folder, but here is no icons named close*, maximize*, and I can't find them in other folders.

**Comment by actionless** [comment]
gtk CSD is a separate case, you can style it somehow like that:

```css
.titlebutton.minimize image {
 opacity: 0;
}
.titlebutton.minimize {
 background: url('/path./to/image.png')  no-repeat center center;
}
```
